# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-06 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruithut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.TextField(blank=True, db_column='TICKET', null=True)),
                ('units', models.FloatField(blank=True, db_column='UNITS', null=True)),
                ('price', models.FloatField(blank=True, db_column='PRICE', null=True)),
                ('reference', models.IntegerField(blank=True, db_column='REFERENCE', null=True)),
                ('code', models.IntegerField(blank=True, db_column='CODE', null=True)),
                ('name', models.TextField(blank=True, db_column='NAME', null=True)),
                ('pricebuy', models.FloatField(blank=True, db_column='PRICEBUY', null=True)),
                ('pricesell', models.FloatField(blank=True, db_column='PRICESELL', null=True)),
                ('datenew', models.TextField(blank=True, db_column='DATENEW', null=True)),
                ('payment', models.TextField(blank=True, db_column='PAYMENT', null=True)),
                ('total', models.FloatField(blank=True, db_column='TOTAL', null=True)),
                ('transid', models.TextField(blank=True, db_column='TRANSID', null=True)),
                ('catergory', models.TextField(blank=True, db_column='CATERGORY', null=True)),
            ],
            options={
                'db_table': 'fruithut',
                'managed': False,
            },
        ),
    ]
